<!--
  ~ All Rights Reserved
  ~
  ~ Copyright (c) 2025. Kof22
  ~
  ~ THE CONTENTS OF THIS PROJECT ARE PROPRIETARY AND CONFIDENTIAL.
  ~ UNAUTHORIZED COPYING, TRANSFERRING, OR REPRODUCTION OF ANY PART OF THIS PROJECT, VIA ANY MEDIUM, IS STRICTLY PROHIBITED.
  ~
  ~ The receipt or possession of the source code and/or any parts thereof does not convey or imply any right to use them
  ~ for any purpose other than the purpose for which they were provided to you.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.kingsrook.unified</groupId>
  <artifactId>unified-parent</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <modules>
    <module>Kingsrook/qqq</module>
    <module>Kof22/Website</module>
     <module>Kof22/Website-CD-Pipeline</module>
  </modules>
</project>
